### ISSUE TITLE
Tag Pypi releases on GitHub

### ISSUE THREAD

**Issue by colemickens** [iwalton3/python-mpv-jsonipc#1]
Hi. When we package python packages for nixpkgs, we try to pull source from GitHub so that tests are included. Even though there aren't tests yet, I'd like to follow that pattern.

It's most easily followed when releases are tagged on Git too. Can you do this so I can package a released version for nixpkgs? context: https://github.com/NixOS/nixpkgs/pull/77884

Thanks!

**Comment by iwalton3** [comment]
Done. Note that version 1.0.0 was purged from the history due to a licensing issue with a Windows Pipe library.

**Comment by iwalton3** [comment]
I also added missing tags for jellyfin-apiclient-python, jellyfin-mpv-shim, and plex-mpv-shim.

**Comment by colemickens** [comment]
Thanks! And thank you for these projects!
