### ISSUE TITLE
Problem when a command has the same name as a property

### ISSUE THREAD

**Issue by varenc** [iwalton3/python-mpv-jsonipc#10]
`vf` is both a command and a property.

Because commands are added to the MPV object [after properties are](https://github.com/iwalton3/python-mpv-jsonipc/blob/master/python_mpv_jsonipc.py#L432), this means that `mpv.vf(...)` issues a vf command and there's no `mpv.vf` to get the `vf` property.

```
In [1]: from python_mpv_jsonipc import MPV

In [2]: mpv = MPV(start_mpv=False, ipc_socket="/tmp/mpv.sock");

In [3]: mpv.vf()
---------------------------------------------------------------------------
MPVError                                  Traceback (most recent call last)
<ipython-input-3-429ca6751f2e> in <module>
----> 1 mpv.vf()

/usr/local/lib/python3.8/site-packages/python_mpv_jsonipc.py in wrapper(*args)
    594     def _get_wrapper(self, name):
    595         def wrapper(*args):
--> 596             return self.command(name, *args)
    597         return wrapper
    598
```

Not sure what the most elegant solution is, but in the mean time I used this simple hack to allow me to fetch the `vf` property.

```
from python_mpv_jsonipc import MPV
mpv = MPV(start_mpv=False, ipc_socket="/tmp/mpv.sock");
mpv.get_property=mpv._get_wrapper("get_property")
mpv.get_property('vf')
```

Now I can just run `mpv.get_property('vf')`.  This doesn't already exist because `get_property` is a separate JSON IPC command and not a property or input command.

Would it be reasonable to extend the MPV object with a `get_property` attribute? If so, can submit a simple PR.

Cheers!

**Comment by iwalton3** [comment]
I made a fix where commands which conflict with properties are mapped to `command_name_cmd` instead.

**Comment by iwalton3** [comment]
The only two commands this happens for are `vf` and `af`.
