### ISSUE TITLE
How to hide the main MPV window then playing audio on Windows?

### ISSUE THREAD

**Issue by silvioprog** [iwalton3/python-mpv-jsonipc#12]
Hi.

First, thanks a lot for this awesome project!

So, I'm playing radio via streaming on Windows, something like this:

```python
mpv = MPV()
mpv.play('http://s1.myradiostream.com:12508/listen.mp3')
...
```

however, it displays the main MPV window as follow:

![Captura de tela 2021-12-18 223112](https://user-images.githubusercontent.com/1456829/146660421-fc2e832e-48b9-4344-ac3d-3fe382f1ec8c.png)

so, is there any option to hide this window?

TIA for any help!

**Comment by iwalton3** [comment]
I believe there is a “no audio display” option.

**Comment by silvioprog** [comment]
So, it can be hidden by flag [`--force-window=no`](https://mpv.io/manual/master/#options-force-window). Is there any option to specify it to the mpv instance?

**Comment by iwalton3** [comment]
Yes when you create the mpv instance pass the argument, or, for many arguments you can just set them on the mpv object after starting it.

Tip! Use the python interactive console to figure out what the configurable values are.

**Comment by silvioprog** [comment]
Hm, found the `__setattr__` method, worked, but the window is shown and hidden after around 1 second. What do you think about allowing extra arguments before spawning the mpv executable? Something (`*args`?) to be expanded here: https://github.com/iwalton3/python-mpv-jsonipc/blob/271f831fcf9a9951e1e54d03dbe33944ff1b0ab2/python_mpv_jsonipc.py#L220

Even an `extra_args` property would be very useful...

**Comment by iwalton3** [comment]
Use kwargs. For instance `mpv = MPV(force_window=False)` which will be translated to `--force-window=no` at runtime.

**Comment by silvioprog** [comment]
Woooooow, it worked like a charm! Thanks a lot for this tip! 🤩🤩🤩
