### ISSUE TITLE
module name

### ISSUE THREAD

**Issue by deadnews** [iwalton3/python-mpv-jsonipc#3]
https://github.com/iwalton3/python-mpv-jsonipc/blob/0b28a6efed690c7f2868ab2ea7e6f66365724ab3/README.md#L26

↓
>ModuleNotFoundError: No module named 'python_mpv_jsonrpc'

Maybe it should be:
```python
from python_mpv_jsonipc import MPV
```
?

**Comment by iwalton3** [comment]
I have fixed the README.
