### ISSUE TITLE
asyncio support?

### ISSUE THREAD

**Issue by tonycpsu** [iwalton3/python-mpv-jsonipc#5]
Just wondering if you might have any plans to support use of this controller via asyncio coroutines instead of threads.  There's someone developing a similar interface [here](https://github.com/marios8543/aio-mpv-jsonipc) with asyncio support, but your interface is more full-featured with property observers and the like.  Before I try to Frankenstein together the two projects, is this something you have any interest in supporting?

**Comment by iwalton3** [comment]
I would say that improving the other one is probably a better idea. This library is very thread oriented, especially with the blocking property get/set calls. (The primary goal was to support a nearly drop-in replacement of the C API-based python-mpv library.)

**Comment by tonycpsu** [comment]
Fair enough.  Thanks!

**Comment by tonycpsu** [comment]
@iwalton3, I'm borrowing heavily from this project for some PRs to be submitted for aio-mpv-jsonipc.  It's MIT-licensed and this is Apache licensed -- both are permissive, but MIT more so.  Just seeing if you have any issues with this code being included in the other project, and how you want to be credited.

**Comment by iwalton3** [comment]
I have no issues with the code being used as long as it complies with the license. I hope it is helpful for your work.
