### ISSUE TITLE
Cannot disable key bindings

### ISSUE THREAD

**Issue by Neraste** [iwalton3/python-mpv-jsonipc#7]
Using mpv 0.33, I can disable key bindings manually by passing `--no-input-default-bindings`, but using the latest release of this package, setting `no_input_default_bindings` to True on an MPV instance does not have any effect.

Is it possible to support this parameter?

**Comment by iwalton3** [comment]
Whatever arguments you pass through the constructor should just be directly sent to MPV, but it looks like some boolean options don't follow the standard.

Maybe try `input_default_bindings=False`? It would be nice if that worked because that's how the C API works.

**Comment by Neraste** [comment]
Thanks, that did the trick. It's quite confusing indeed that some Booleans from the documentation cannot be used straight.
